local_costmap:
  global_frame: locobot/odom
  robot_base_frame: locobot/base_footprint

  update_frequency: 20.0
  publish_frequency: 20.0
  transform_tolerance: 0.5  

  static_map: false  
  rolling_window: true
  width: 5.0
  height: 5.0
  resolution: 0.05


