controller_list:
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [waist, shoulder, elbow, forearm_roll, wrist_angle, wrist_rotate, right_finger, left_finger]
  - name: "gripper_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints: [right_finger, left_finger]
